# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.4'

volumes:
  customsOrg:

networks:
  cr_network:
     external:
        name: cr_network

services:
  zookeeper0:
    container_name: zookeeper0
    image: hyperledger/fabric-zookeeper:0.4.14
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=0.0.0.0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == ip-172-31-47-47
                    # - node.role == manager
    ports:
      - target: 2181
        published: 2181
        mode: host
      - target: 2888
        published: 2888
        mode: host
      - target: 3888
        published: 3888
        mode: host
    extra_hosts:
    - "zookeeper1:172.31.40.38"
    - "zookeeper2:172.31.40.83"
    networks:
      cr_network:
        aliases:
          - zookeeper0

  zookeeper1:
    container_name: zookeeper1
    image: hyperledger/fabric-zookeeper:0.4.14
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zookeeper2:2888:3888
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == ip-172-31-40-38
                    # - node.role == manager
    ports:
      - target: 2181
        published: 2181
        mode: host
      - target: 2888
        published: 2888
        mode: host
      - target: 3888
        published: 3888
        mode: host
    extra_hosts:
    - "zookeeper0:172.31.47.47"
    - "zookeeper2:172.31.40.83"
    networks:
      cr_network:
        aliases:
          - zookeeper1

  zookeeper2:
    container_name: zookeeper2
    image: hyperledger/fabric-zookeeper:0.4.14
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=0.0.0.0:2888:3888
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == ip-172-31-40-83
                    # - node.role == manager
    ports:
      - target: 2181
        published: 2181
        mode: host
      - target: 2888
        published: 2888
        mode: host
      - target: 3888
        published: 3888
        mode: host
    extra_hosts:
    - "zookeeper0:172.31.47.47"
    - "zookeeper1:172.31.40.38"
    networks:
      cr_network:
        aliases:
          - zookeeper2
            
