# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.4'

volumes:
  customsOrg:

networks:
  cr_network:
     external:
        name: cr_network

services:

  customsOrg:
    container_name: peer0.customsOrg.chainrefund.com
    image: hyperledger/fabric-peer:1.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=cr_network
      - FABRIC_LOGGING_SPEC=DEBUG
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.customsOrg.chainrefund.com
      - CORE_PEER_ADDRESS=peer0.customsOrg.chainrefund.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.customsOrg.chainrefund.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.customsOrg.chainrefund.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.customsOrg.chainrefund.com:9051
      - CORE_PEER_LOCALMSPID=CustomsOrgMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb_customs:6984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ~/crypto-config/peerOrganizations/customsOrg.chainrefund.com/peers/peer0.customsOrg.chainrefund.com/msp:/etc/hyperledger/fabric/msp
        - ~/crypto-config/peerOrganizations/customsOrg.chainrefund.com/peers/peer0.customsOrg.chainrefund.com/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    deploy:
       mode: replicated
       replicas: 1
       restart_policy:
          condition: on-failure
       placement:
           constraints:
              - node.hostname == ip-172-31-47-47
    ports:
            - published: 9051
              target: 9051
              mode: host
            - published: 9053
              target: 9053
              mode: host
    extra_hosts:
    - "orderer.chainrefund.com:172.31.32.53"
    - "peer0.chainrefundOrg.chainrefund.com:172.31.33.161"
    - "couchdb_customs:172.31.47.47"
    - "peer0.merchantsOrg.chainrefund.com:172.31.40.38"
    - "peer0.nttOrg.chainrefund.com:172.31.40.83"
    networks:
       cr_network:
          aliases:
             - peer0.customsOrg.chainrefund.com

  couchdb_customs:
    container_name: couchdb_customs
    image: hyperledger/fabric-couchdb:0.4.14
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    deploy:
       mode: replicated
       replicas: 1
       restart_policy:
          condition: on-failure
       placement:
          constraints:
             - node.hostname == ip-172-31-47-47
    ports:
            - published: 6984
              target: 5984
              mode: host
    networks:
       - cr_network


